### PR TITLE
Added settings persistence

### PR DESCRIPTION
**Pull request by rimadoma**
The settings for the plugins in _Plugins>Process>_ (`package process3d`) now persist

Also did some general maintenance, fixing deprecated calls etc.

### CODE REVIEW

**Comment by ctrueden** [comment]
I wish you could have used ImageJ2 style instead, where preferences are already persisted... was the goal to minimize changes to preserve backwards compatibility?

**Comment by rimadoma** [comment]
No, but I have no idea how to turn all of this into IJ 2. Maybe some day if I have the time. Sorry.

**Comment by ctrueden** [comment]
Sorry for my cryptic comments. What I meant was: using parameterized commands and scripts in ImageJ2 automatically persists the last used settings. So you don't have to manually call `ij.Prefs` for that. (And if you did need to persist some settings manually in IJ2 for some reason—even though it isn't common—you could use the `PrefService` to do it.)

That said, I understand that converting existing uses of `GenericDialog` over to parameterized commands or scripts might be too involved. I'd have to study the code in more detail to judge here. Happy to go over it in detail via voice chat after I return from AQLM next week. Or in person at the next hackathon.

**Comment by rimadoma** [comment]
@ctrueden OK, sounds good. I was just worried that converting the settings to `\@Parameters` would cause a whole bunch of IJ1 -- IJ2 incompatibility issues

**Pull request merged**
